# Generated by Django 3.0 on 2019-12-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=100)),
                ('s_t', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('cr_us', models.CharField(max_length=10)),
                ('cr_ects', models.IntegerField()),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('enrolled', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('faculty', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
            ],
        ),
    ]
