# Generated by Django 3.0 on 2019-12-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrolled',
        ),
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='room',
        ),
        migrations.RemoveField(
            model_name='course',
            name='s_t',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionname', models.CharField(max_length=10)),
                ('days', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('enrolled', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('faculty', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Course')),
            ],
        ),
    ]
